package dev.gtcl.reddit

const val POST_KEY = "post"
const val POST_PAGE_KEY = "post_page"
const val POSITION_KEY = "position"
const val COMMENT_KEY = "comment"
const val SUBREDDIT_KEY = "subreddit"
const val URL_KEY = "url"
const val FULL_CONTEXT_URL_KEY = "full_context"
const val USER_KEY = "user"
const val MEDIA_KEY = "media"
const val CURRENT_USER_KEY = "current_user"
const val SELECTED_SUBREDDITS_KEY = "selected_subreddits"
const val MULTI_KEY = "multireddit_key"
const val FLAIRS_KEY = "flairs"
const val FLAIR_SELECTED_KEY = "flair_selected"
const val ITEM_KEY = "item"
const val NEW_REPLY_KEY = "new_reply"
const val PREFERENCES_KEY = "preferences"
const val EXPAND_REPLIES_KEY = "expand"
const val REPORT_KEY = "report"
const val NSFW_KEY = "nsfw"
const val SPOILER_KEY = "spoiler"
const val GET_NOTIFICATIONS_KEY = "notifications"
const val MANAGE_POST_KEY = "manage_post"
// Draft
const val DRAFT_KEY = "draft"
const val TO_KEY = "to"
const val SUBJECT_KEY = "subject"
const val MESSAGE_KEY = "message"

// For listing fragments
const val PROFILE_INFO_KEY = "profile_info"
const val POST_SORT_KEY = "post_sort"
const val TIME_KEY = "time"
const val MESSAGE_WHERE_KEY = "message_where"
const val USE_TRENDING_ADAPTER_KEY = "use_trending_adapter"
const val SUBREDDIT_WHERE_KEY = "subreddit_where"
const val PAGE_SIZE_KEY = "page_size"
const val LISTING_KEY = "listing"