package dev.gtcl.reddit

const val POST_KEY = "post"
const val POST_PAGE_KEY = "post_page"
const val POSITION_KEY = "position"
const val POST_BUNDLE_KEY = "post_bundle"
const val SUBREDDIT_KEY = "subreddit"
const val URL_KEY = "url"
const val URLS_KEY = "urls"
const val URL_TYPE_KEY = "url_type"
const val USER_KEY = "user"
const val MEDIA_KEY = "media"
const val CURRENT_USER_KEY = "current_user"
const val SELECTED_SUBREDDITS_KEY = "selected_subreddits"
const val MULTI_KEY = "multireddit_key"
const val FLAIRS_KEY = "flairs"
const val FLAIR_SELECTED_KEY = "flair_selected"
const val FLAIR_EDIT_KEY = "flair_edit"
const val ALBUM_KEY = "album"
const val ITEM_KEY = "item"

// For listing fragments
const val PROFILE_INFO_KEY = "profile_info"
const val POST_SORT_KEY = "post_sort"
const val TIME_KEY = "time"
const val MESSAGE_WHERE_KEY = "message_where"
const val USE_TRENDING_ADAPTER_KEY = "use_trending_adapter"
const val SUBREDDIT_WHERE_KEY = "subreddit_where"
const val PAGE_SIZE_KEY = "page_size"
const val LISTING_KEY = "listing"