package dev.gtcl.astro

const val POST_KEY = "post"
const val POST_PAGE_KEY = "post_page"
const val POSITION_KEY = "position"
const val COMMENT_KEY = "comment"
const val SUBREDDIT_KEY = "subreddit"
const val URL_KEY = "url"
const val USER_KEY = "user"
const val MEDIA_KEY = "media"
const val PLAY_WHEN_READY_KEY = "play_when_ready"
const val MEDIA_ITEMS_KEY = "media_items"
const val CURRENT_USER_KEY = "current_user"
const val SELECTED_SUBREDDITS_KEY = "selected_subreddits"
const val MULTI_KEY = "multireddit_key"
const val FLAIRS_KEY = "flairs"
const val FLAIR_SELECTED_KEY = "flair_selected"
const val ITEM_KEY = "item"
const val NEW_REPLY_KEY = "new_reply"
const val PREFERENCES_KEY = "preferences"
const val EXPAND_REPLIES_KEY = "expand"
const val REPORT_KEY = "report"
const val DARK_SETTINGS_KEY = "dark_settings"
const val NSFW_KEY = "nsfw"
const val SPOILER_KEY = "spoiler"
const val NSFW_THUMBNAIL_KEY = "blur_nsfw_thumbnail"
const val DEFAULT_POST_SORT_KEY = "default_post_sort"
const val GET_NOTIFICATIONS_KEY = "notifications"
const val MANAGE_POST_KEY = "manage_post"
const val ALBUM_KEY = "album_name"
const val COPY_KEY = "copy"

// Draft
const val DRAFT_KEY = "draft"
const val TO_KEY = "to"
const val SUBJECT_KEY = "subject"
const val MESSAGE_KEY = "message"

// For listing fragments
const val PROFILE_INFO_KEY = "profile_info"
const val POST_SORT_KEY = "post_sort"
const val TIME_KEY = "time"
const val MESSAGE_WHERE_KEY = "message_where"
const val SUBREDDIT_WHERE_KEY = "subreddit_where"
const val LISTING_KEY = "listing"